config/routes.rb
 require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: "questions#index"

  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}

  devise_scope :user do
    get 'edit_email/:id', to: 'registrations#edit_email', as: 'edit_email'
    patch 'update_email/:id', to: 'registrations#update_email', as: 'update_email'
  end

  get :search, to: 'search#index'

  concern :votable do
    member do
      patch 'like'
      patch 'dislike'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create], shallow: true do
        resources :answers, only: %i[index show create]
      end
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :update, :destroy], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :attachments, shallow: true, only: %i[destroy]
    resources :answers, shallow: true, concerns: [:votable, :commentable], only: %i[create destroy update] do
      resources :attachments, shallow: true, only: %i[destroy]
      patch :find_best_answer, on: :member
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end


  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  belongs_to :user

  validates :title, :body, presence: true

  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank

  after_create :update_reputation
  after_create :create_subscription

  private

  def update_reputation
    CalculateReputationJob.perform_later(self)
  end

  def create_subscription
    subscriptions.create(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question, serializer: SingleQuestionSerializer
  end

  def create
    @question = current_resource_owner.questions.create(question_params)
    respond_with @question, serializer: SingleQuestionSerializer
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, only: [ :update, :new, :create, :show ]
  before_action :find_question, only: [ :show, :edit, :update, :destroy ]
  before_action :build_answer, only: :show
  after_action :publish_question, only: :create

  authorize_resource

  respond_to :html, :js, :json

  def index
    respond_with(@questions = Question.all)
  end

  def show
    @subscription = @question.subscriptions.where(user_id: current_user.id).first
    respond_with @question
  end

  def new
    respond_with(@question = current_user.questions.new)
  end

  def edit; end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to @question, notice: "Your question successfully created."
    else
      render :new, notice: 'Your question was not created.'
    end
  end

  def update
    @question.update(question_params) if current_user.author_of?(@question)
    respond_with @question
  end


  def destroy
    respond_with(@question.destroy) if current_user.author_of?(@question)
  end

  private

  def build_answer
    @answer = @question.answers.new
  end

  def find_question
    @question = Question.find(params[:id])
    gon.question_id = @question.id
    gon.question_user_id = @question.user_id
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :destroy])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast 'questions', ApplicationController.render(
      partial: 'questions/collection_item', locals: { question: @question }, layout: false
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_collection_item.html.slim
li
  .collection-item id="#{question.id}"
    = link_to question.title, question_path(question)

app/views/questions/index.html.slim
.search
  = form_for :search, url: search_path, method: :get do |f|
    = f.text_field :query
    = f.select :resource, Search::OBJECTS, { include_blank: 'All' }
    p
    = f.submit 'Search'

p= link_to  'Ask question', new_question_path

ul.questions
  - cache collection_cache_key_for :question do
    - @questions.each do |question|
      = render 'collection_item', question: question
    end

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question
= form_with model: @question do |f|
  = f.label :title
  p
  = f.text_field :title
  p
  p
  = f.label :body
  p
  = f.text_area :body
  p
  =render 'shared/nested_form', form: f, resource: @question
  p
  = f.submit 'Create'

app/views/questions/show.html.slim
cache @question do
  div
    .question
      p
      = @question.title
      p
      = @question.body
      p

    .question_rating
      = render 'shared/rating', resource: @question
    p

    .question_comments
      - if user_signed_in?
      details
        summary Your comment:
        p
          = render 'comments/form', resource: @question
        p

      - if @question.comments.size > 1
          .all_question_comments
            details
              summary Comments
              p
                = render @question.comments
      p

    .subscription
      -if user_signed_in?
        -if current_user.subscribe?(@question)
          p= link_to  "Unsubscribe", subscription_path(@subscription), method: :delete, remote: true
        -else
          p= link_to  "Subscribe", question_subscriptions_path(@question), method: :post, remote: true

    ul
      - @question.attachments.each do |a|
        li= link_to a.file.identifier, a.file.url

        -if current_user.author_of?(@question)
          = link_to  "delete", attachment_path(a), method: :delete, remote: true

  -if current_user.present?
    details
      summary Your answer:
      p
        = render 'answers/form'

  .answers
    details
      summary Answers:
      p
        = render 'answers/answers'

  -if current_user&.author_of?(@question)

    p= link_to 'Delete question', question_path(@question), method: :delete

    p= link_to 'Edit question', '', class: 'edit-question-link', data: { question_id: @question.id }

    details
      summary Edit question:
      p
      =form_with model: @question, remote: true do |f|
        = f.label :title, 'New title'
        p
        = f.text_field :title
        p
        p
        = f.label :body, 'New body'
        p
        = f.text_area :body
        p
        = f.submit 'Save'

app/views/questions/update.js.erb
<% if  @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.question_errors').append('<%= j message %><br>')
  <% end %>
<% else %>
  $('.question_errors').html('')
  $('.edit-question-link').click(function (e) {
    console.log('event')
    e.preventDefault();
    $('.edit_question').show();
    $(this).hide();
  })
  location.reload()
<% end %>