config/routes.rb
 require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: "questions#index"

  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}

  devise_scope :user do
    get 'edit_email/:id', to: 'registrations#edit_email', as: 'edit_email'
    patch 'update_email/:id', to: 'registrations#update_email', as: 'update_email'
  end

  get :search, to: 'search#index'

  concern :votable do
    member do
      patch 'like'
      patch 'dislike'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create], shallow: true do
        resources :answers, only: %i[index show create]
      end
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :update, :destroy], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :attachments, shallow: true, only: %i[destroy]
    resources :answers, shallow: true, concerns: [:votable, :commentable], only: %i[create destroy update] do
      resources :attachments, shallow: true, only: %i[destroy]
      patch :find_best_answer, on: :member
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end


  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_many :attachments , as: :attachable

  validates :body, presence: true

  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank

  scope :by_best, -> { order(best: :desc) }

  def find_best_answer
    transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end

  after_create :update_reputation
  after_create :send_notification

  private

  def update_reputation
    CalculateReputationJob.perform_later(self)
  end

  def send_notification
    AnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  respond_to :js, :json

  before_action :authenticate_user!, only: [ :update, :new, :create ]
  before_action :find_question, only: %i[ create ]
  before_action :find_answer, only: %i[ update destroy find_best_answer ]
  after_action :publish_answer, only: :create

  authorize_resource

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    if @answer.save
      redirect_to @question, notice: 'Your answer successfully created.'
    else
      render 'questions/show', notice: 'Your answer was not created.'
    end
  end

  def update
    @answer.update(answer_params) if current_user.author_of?(@answer)
    respond_with @answer
  end

  def destroy
    @answer.destroy if current_user.author_of?(@answer)
    redirect_to question_path(@answer.question)
  end

  def find_best_answer
    @question = @answer.question
    @answer.find_best_answer if current_user.author_of?(@question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :destroy])
  end

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast(
      "answers_question_#{@question.id}",
      answer: @answer,
      attachments: @answer.attachments,
      rating: @answer.rating
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_question, only: %i[index create]

  def index
    @answers = @question.answers
    respond_with @answers
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer, serializer: SingleAnswerSerializer
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_resource_owner
    @answer.save
    render json: @answer, serializer: SingleAnswerSerializer
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answers.html.slim
  - @question.answers.by_best.each do |answer|
      -if answer.persisted?
      - cache answer do
          div class="answer_#{answer.id}"
            p= answer.body

            .answer_rating
              = render 'shared/rating', resource: answer

            .answer_attachments
              ul
                -answer.attachments.each do |a|
                  li = link_to  a.file.identifier, a.file.url

                  -if current_user.author_of?(answer)
                    = link_to  "delete", attachment_path(a), method: :delete, remote: true

            .answer_comments
              - if user_signed_in?
                => link_to 'Add comment', '', class: 'add-comment-link', data: {resource_id: answer.id, resource_type: 'answer'}
                = render 'comments/form', resource: answer
              - if answer.comments.size > 1
                h4= 'Comments:'
                = render answer.comments

            -if current_user&.author_of?(answer.question)
              p= link_to "Choose the best", find_best_answer_answer_path(answer), method: :patch, remote: true
            else
              p You need to be an author of question to choose best answer.

            -if current_user&.author_of?(answer)
              p= link_to 'Delete answer', answer, method: :delete

              p= link_to 'Edit answer', '', class: 'edit-answer-link', data: { answer_id: answer.id }

              = form_with model: answer, remote: true, html: { id: "edit-answer-#{answer.id}", class: 'edit-form'} do |f|
                = f.label :body, 'New answer'
                = f.text_area :body

                = f.submit 'Save'

            else
              p You need to sign in or sign up to delete the answer.

app/views/answers/_form.html.slim
= render 'shared/errors', resource: @answer

= form_with model: [@question, @answer], local: true do |f|
  = f.text_area :body

  p Attachments
  p
    = render 'shared/nested_form', form: f, resource: @answer

  br
  = f.submit 'Create answer'

app/views/answers/create.js.erb
<% if  @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.errors').append('<%= j message %><br>')
  <% end %>
<% else %>
  $('.errors').html('')
  $('.answers').append('<%= j render @answer %>')
<% end %>
$('form#answer_body').val('')

app/views/answers/destroy.js.erb
$(".answer-<%= @answer.id %>").remove()

app/views/answers/find_best_answer.js.erb
$('.answers').html('<%= @question.answers.by_best.each do |answer|  %>')
  <%= j answer.body %>
<% end %>

app/views/answers/update.js.erb
<% if  @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.errors').append('<%= j message %><br>')
  <% end %>
<% else %>
  $('.errors').html('')
  $('.edit-answer-link').click(function (e) {
    e.preventDefault();
    $('.edit_answer').show();
    $(this).hide();
    answer_id = $(this).data('answerId');
    $('form#edit-answer-' + answer_id).show();
  })
  location.reload()
<% end %>